name: PlatformIO CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.example }}@${{ matrix.board }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example: [basic]
        board: [m5stack-cores3, m5stack-stamps3, m5stick-c]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
      - name: Cache pio
        uses: actions/cache@v4
        with:
          path: ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install PlatformIO
        run: pip install --upgrade platformio
      - name: Build
        run: pio run -e ${{ matrix.example }}_${{ matrix.board }}
